/* ============================================================
 * synthesis_window_table.h  --  1024-pt OLA synthesis window, Q15
 *
 * The synthesis window is derived from the analysis window (Hamming)
 * by dividing by the steady-state overlap-add gain:
 *
 *   gain = sum_{k=0}^{3} w_a[i + k*HOP]^2   (constant = 1.5896 for
 *                                              Hamming at 75% overlap)
 *
 *   synthesis_hamming_q15[n] = round( hamming[n] / gain * 32768 )
 *
 * This satisfies the COLA condition exactly:
 *   sum_{k=0}^{3} w_a[i+k*H] * w_s[i+k*H] = 1.0  for all i in [0,HOP)
 *
 * Residual Q15 quantisation error: < 0.004% (verified in Python).
 *
 * Usage: replace hamming_q15[] with synthesis_hamming_q15[] ONLY in
 *        stft_overlap_add().  The analysis window (stft_push_hop) must
 *        continue to use hamming_q15[].
 *
 * Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND.
 * ============================================================ */

#ifndef TMS320_SYNTHESIS_WINDOW_TABLE_H
#define TMS320_SYNTHESIS_WINDOW_TABLE_H

#include "fixed_point.h"
#include "../config.h"

/* synthesis_hamming_q15[n] = hamming[n] / 1.5896, Q15.
 * Range: [1649, 20614] (vs hamming [2621, 32767]).
 * Memory: 2 KB (.const in SARAM). */
extern const q15_t synthesis_hamming_q15[N_FFT];

#endif /* TMS320_SYNTHESIS_WINDOW_TABLE_H */
