/* ============================================================
 * twiddle_table.h  --  1024-pt FFT twiddle factors, Q15
 *
 * Definitions live in twiddle_table.c so the TI C5500 linker keeps a
 * single copy in .const regardless of how many TUs include this header.
 *
 *   W_N^k = exp(-j * 2*pi*k / N),   k = 0 .. N/2 - 1
 *
 * Forward FFT uses (twiddle_re_q15[k], twiddle_im_q15[k]).
 * Inverse FFT conjugates the imaginary part on the fly.
 * Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND.
 * ============================================================ */

#ifndef TMS320_TWIDDLE_TABLE_H
#define TMS320_TWIDDLE_TABLE_H

#include "fixed_point.h"
#include "../config.h"

extern const q15_t twiddle_re_q15[N_FFT / 2];
extern const q15_t twiddle_im_q15[N_FFT / 2];

#endif /* TMS320_TWIDDLE_TABLE_H */
