/* ============================================================
 * window_table.h  --  1024-pt periodic Hamming window, Q15
 *
 * Definition lives in window_table.c so the TI C5500 linker keeps a
 * single copy in .const regardless of how many TUs include this header.
 *
 *   w[n] = 0.54 - 0.46 * cos(2*pi*n / N),   n = 0 .. N-1
 *
 * Maximum value 1.0 is stored as 32767 (Q15_ONE - 1).
 * Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND.
 * ============================================================ */

#ifndef TMS320_WINDOW_TABLE_H
#define TMS320_WINDOW_TABLE_H

#include "fixed_point.h"
#include "../config.h"

extern const q15_t hamming_q15[N_FFT];

#endif /* TMS320_WINDOW_TABLE_H */
