#!/usr/bin/env python3
"""Generate Q15 constant tables for the TMS320 simulator.

Outputs:
  src/util/window_table.h    -- 1024-pt periodic Hamming window in Q15
  src/util/twiddle_table.h   -- 1024-pt forward-FFT twiddle factors in Q15

Both files contain only `static const` data; no runtime computation.
"""

import numpy as np
from pathlib import Path

N_FFT = 1024

ROOT = Path(__file__).resolve().parent.parent


def float_to_q15(x: float) -> int:
    v = x * 32768.0
    if v > 32767.0:
        v = 32767.0
    if v < -32768.0:
        v = -32768.0
    return int(round(v))


def emit_array(name: str, values: list[int], cols: int = 8) -> str:
    lines = [f"static const q15_t {name}[{len(values)}] = {{"]
    for i in range(0, len(values), cols):
        chunk = values[i:i + cols]
        lines.append("    " + ", ".join(f"{v:6d}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def gen_window():
    # MATLAB hamming(N, 'periodic'): w[n] = 0.54 - 0.46*cos(2*pi*n/N), n = 0..N-1
    n = np.arange(N_FFT)
    w = 0.54 - 0.46 * np.cos(2.0 * np.pi * n / N_FFT)
    q = [float_to_q15(v) for v in w]
    body = emit_array("hamming_q15", q)
    # Strip the "static const" qualifier from the emitted definition:
    body_def = body.replace(
        "static const q15_t hamming_q15",
        "MEM_SARAM_RO const q15_t hamming_q15", 1)

    header_text = """/* ============================================================
 * window_table.h  --  1024-pt periodic Hamming window, Q15
 *
 * Definition lives in window_table.c so the TI C5500 linker keeps a
 * single copy in .const regardless of how many TUs include this header.
 *
 *   w[n] = 0.54 - 0.46 * cos(2*pi*n / N),   n = 0 .. N-1
 *
 * Maximum value 1.0 is stored as 32767 (Q15_ONE - 1).
 * Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND.
 * ============================================================ */

#ifndef TMS320_WINDOW_TABLE_H
#define TMS320_WINDOW_TABLE_H

#include "fixed_point.h"
#include "../config.h"

extern const q15_t hamming_q15[N_FFT];

#endif /* TMS320_WINDOW_TABLE_H */
"""
    source_text = f"""/* Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND. */

#include "window_table.h"
#include "../hal/memmap.h"

/* MEM_SARAM_RO marks read-only tables; on chip these live in .const
 * inside SARAM.  On host it's a no-op. */
{body_def}
"""
    (ROOT / "src/util/window_table.h").write_text(header_text)
    (ROOT / "src/util/window_table.c").write_text(source_text)
    print(f"window_table.{{h,c}} written  (max={max(q)}, min={min(q)})")


def gen_twiddle():
    # Forward FFT twiddle: W_N^k = exp(-j * 2*pi*k / N), k = 0 .. N/2 - 1
    # We store real and imaginary parts separately as two Q15 arrays.
    k = np.arange(N_FFT // 2)
    ang = -2.0 * np.pi * k / N_FFT
    re = np.cos(ang)
    im = np.sin(ang)
    re_q = [float_to_q15(v) for v in re]
    im_q = [float_to_q15(v) for v in im]
    body_re = emit_array("twiddle_re_q15", re_q)
    body_im = emit_array("twiddle_im_q15", im_q)
    body_re_def = body_re.replace(
        "static const q15_t twiddle_re_q15",
        "MEM_SARAM_RO const q15_t twiddle_re_q15", 1)
    body_im_def = body_im.replace(
        "static const q15_t twiddle_im_q15",
        "MEM_SARAM_RO const q15_t twiddle_im_q15", 1)
    header_text = """/* ============================================================
 * twiddle_table.h  --  1024-pt FFT twiddle factors, Q15
 *
 * Definitions live in twiddle_table.c so the TI C5500 linker keeps a
 * single copy in .const regardless of how many TUs include this header.
 *
 *   W_N^k = exp(-j * 2*pi*k / N),   k = 0 .. N/2 - 1
 *
 * Forward FFT uses (twiddle_re_q15[k], twiddle_im_q15[k]).
 * Inverse FFT conjugates the imaginary part on the fly.
 * Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND.
 * ============================================================ */

#ifndef TMS320_TWIDDLE_TABLE_H
#define TMS320_TWIDDLE_TABLE_H

#include "fixed_point.h"
#include "../config.h"

extern const q15_t twiddle_re_q15[N_FFT / 2];
extern const q15_t twiddle_im_q15[N_FFT / 2];

#endif /* TMS320_TWIDDLE_TABLE_H */
"""
    source_text = f"""/* Generated by tools/gen_tables.py.  DO NOT EDIT BY HAND. */

#include "twiddle_table.h"
#include "../hal/memmap.h"

{body_re_def}

{body_im_def}
"""
    (ROOT / "src/util/twiddle_table.h").write_text(header_text)
    (ROOT / "src/util/twiddle_table.c").write_text(source_text)
    print(f"twiddle_table.{{h,c}} written  ({N_FFT//2} entries, real range [{min(re_q)}, {max(re_q)}])")


if __name__ == "__main__":
    gen_window()
    gen_twiddle()
